module.exports = {
  colors: {
    default: '#fff0',
    main: '#000',
    second: '#333',
    error: '#bb2124',
    success: '#22bb33',
    info: '#5bc0de',
    gray: '#aaaaaa',
    text: '#000',
  },
  fontFamily: {
    default: 'roboto',
    bold: '',
    extraBold: '',
    semiBold: '',
    normal: '',
    light: '',
    extraLight: '',
    medium: '',
    thin: '',
  },
  fontSize: {
    default: 10,
    xs: 9,
    sm: 14,
    md: 20,
    lg: 25,
    xl: 30,
    xxl: 35,
  },
  spaces: {
    horizontal: 20,
    vertical: 20,
    divide: 10,
    stander: 5,
  },
};
